### ISSUE TITLE
Emojify settings not showing up

### ISSUE THREAD

**Issue by Cypphi** [ViniDalvino/emojify#1]
Hey, I'm not sure if this is a bug or that it's another plugin messing with Emojify. But it's settings don't show up. Are there any plugins known for breaking this plugin?

**Comment by TheEpicFace007** [comment]
No there’s no known plug-in to break the plug-in

Can you show me what the dev console show up when you load the plugins

**Comment by Cypphi** [comment]
Here
![image](https://user-images.githubusercontent.com/64902193/116585502-c5eec180-a918-11eb-8ea7-769c66d716ba.png)

**Comment by TheEpicFace007** [comment]
I pushed a update that fix the issue

**Comment by Cypphi** [comment]
> I pushed a update that fix the issue

Yea i think it works now. Also, is there a list of commands or features anywhere?

**Comment by Cypphi** [comment]
wait nvm, it would be nice if I could disable the plugin so I dont flood every chat i talk in. because whitelisting or blacklisting is kinda annoying. 

Setting the max amount of emojis to 0 still uses 2 emojis btw

**Comment by TheEpicFace007** [comment]
> wait nvm, it would be nice if I could disable the plugin so I dont flood every chat i talk in. because whitelisting or blacklisting is kinda annoying.
> 
> Setting the max amount of emojis to 0 still uses 2 emojis btw

idk why its happening

anyway issue closed
